version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/rimappa?schema=public
      - NEXTAUTH_SECRET=your-super-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=rimappa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 